Dockerfile, QRServer/config.py, docker/entrypoint.sh
Add Docker image for QR server and HTTP server with client
=> Add Docker image

QRServer/common/clienthandler.py, QRServer/common/messages.py, launcher/package-lock.json, launcher/package.json
=> Add handling for broken connections and unsupported characters

server/src/QRServer/common/classes.py, server/src/QRServer/common/clienthandler.py, server/src/QRServer/common/messages.py, server/src/QRServer/db/connector.py, server/src/QRServer/db/migrations.py, server/src/QRServer/db/models.py, server/src/QRServer/game/gameclient.py, server/src/QRServer/game/gameserver.py, server/src/QRServer/lobby/lobbyclient.py, server/tests/test_db.py
Related to #43, adds persisting of results. Still needs calculating the scores and returning them when client joins
=> add persisting of match results

server/src/QRServer/__main__.py, server/src/QRServer/config.py, server/src/QRServer/config_handlers.py, server/src/QRServer/discord/logger.py, server/src/QRServer/discord/webhook.py
Add a Discord webhook for uploading logs.
=> Add Discord logging

server/src/QRServer/__main__.py, server/src/QRServer/common/classes.py, server/src/QRServer/config.py, server/src/QRServer/config_handlers.py, server/src/QRServer/db/connector.py, server/src/QRServer/discord/logger.py, server/src/QRServer/discord/webhook.py, server/src/QRServer/game/gameclient.py, server/src/QRServer/game/gameserver.py, server/src/QRServer/lobby/lobbyclient.py
This makes it easier to write tests
=> Refactor code and get rid of static state

server/src/QRServer/__main__.py
Connector was not being closed properly
=> Fix server stopping and cleanup

server/src/QRServer/__main__.py, server/src/QRServer/common/clienthandler.py, server/src/QRServer/config_handlers.py, server/src/QRServer/db/connector.py, server/src/QRServer/db/models.py, server/src/QRServer/discord/webhook.py, server/src/QRServer/game/gameclient.py, server/src/QRServer/game/gameserver.py, server/src/QRServer/lobby/lobbyclient.py, server/src/QRServer/lobby/lobbyserver.py, server/src/QRServer/server.py
Adding application logger allows setting application-wide logging level which does not affect non-application loggers.
=> Improve logging, add application logger

.github/workflows/server.yml, README.md, server/setup.py, server/src/QRServer/common/clienthandler.py, server/src/QRServer/game/gameclient.py, server/src/QRServer/lobby/lobbyclient.py, server/src/QRServer/server.py, server/tests/it/__init__.py, server/tests/it/test_init.py, server/tests/it/test_lobby.py
Use fully async sockets from asyncio. This also requires dropping support for Python 3.8
=> Use native asyncio sockets

server/src/QRServer/db/connector.py, server/src/QRServer/lobby/lobbyclient.py, server/tests/it/test_lobby.py
=> Ensure communique is broadcasted on join

launcher/postinstall.js
=> Bump ruffle to nightly-2024-03-02

docker/qr/http/index.html
=> Remove development version notice

server/src/QRServer/common/classes.py, server/src/QRServer/common/messages.py, server/src/QRServer/db/connector.py, server/src/QRServer/lobby/lobbyclient.py, server/tests/it/test_lobby.py
=> Implement password changing by users

server/src/QRServer/common/messages.py
This message is not used in the client.
=> Remove unused GameServerAliveResponse

server/setup.py, server/src/QRServer/common/utils.py, server/src/QRServer/config.py, server/src/QRServer/db/connector.py, server/src/QRServer/db/migrations.py, server/src/QRServer/db/models.py, server/src/QRServer/discord/bot.py, server/src/QRServer/server.py, server/tests/it/test_discord_bot.py, server/tests/test_db.py, server/tests/test_discord_bot.py, server/tests/test_utils.py
=> Add discord bot and registration

server/src/QRServer/config.py, server/src/QRServer/lobby/lobbyclient.py
=> Add welcome message sent after joining to lobby

.github/workflows/server.yml, README.md, launcher/postinstall.js, server/setup.py, server/src/QRServer/db/connector.py
This means dropping support for python <3.12
=> Chore: Disable autocommit

server/src/QRServer/common/clienthandler.py
This patch improves exception handling and takes into account more situations where errors occur.
Particularly, it fixes an issue where a client spontaneously starts throwing BrokenPipeError and the server would not let the connection go.
=> Improve exception handling

server/src/QRServer/common/classes.py
Ranked & void match detection assumed all parties were connected when checking the condition, which doesn't have to be true.
**This is not tested, requires testing.**
=> Fix potential race conditions when detecting ranked & void matches

docker/qr/http/index.html
=> misc: add description to webpage's meta

server/src/QRServer/common/classes.py, server/src/QRServer/common/utils.py, server/src/QRServer/db/common.py, server/src/QRServer/db/connector.py, server/src/QRServer/db/migrations.py, server/src/QRServer/db/models.py, server/tests/test_db.py, server/tests/test_messages.py, server/tests/test_utils.py
=> feat: add elo rating system

docker/qr/http/config-ruffle.js
rewrite lobby link leading to quadboard to point to discord server ~~(untested - help needed)~~ tested manually via overrides
=> feat: rewrite quadboard link

docker/etc/nginx/conf.d/default.conf
The client was being timed out because of proxy timeouts.
=> Increase https proxy timeouts

docker/qr/http/styles.css
use touch capabilities detection in browser to determine whether the fullscreen toggle should be visible, fix the display css
=> fix: correct mobile detection for fullscreen

server/src/QRServer/api/api.py, server/tests/it/test_api_lobby.py
It provides the number of players currently in lobby
=> Add /api/v1/lobby/stats endpoint

server/src/QRServer/api/api.py, server/tests/it/test_api_game.py
It provides the player count in game.
=> Add /api/v1/game/stats endpoint
